/* cSpell:disable */
const testObjBase = {
  itemFilter: [
    {
      id: '37',
      name: 'Bruno Compete Hoodie-S-Black',
      IsFeatured: '0',
      inStock: '1',
      stock: '60',
      price: '63',
      cat_1: 'Clothing',
      cat_2: 'Men',
      cat_3: 'Tops',
      cat_4: 'Hoodies & Sweatshirts',
      collections: 'Eco Friendly',
      image_1: 'mh03-black_main.jpg',
      image_2: 'mh03-black_alt1.jpg',
      size: 'M',
      color: 'Black',
    },
    {
      id: '5',
      name: 'Chaz Kangeroo Hoodie-S-Black',
      IsFeatured: '0',
      inStock: '0',
      stock: '0',
      price: '52',
      cat_1: 'Clothing',
      cat_2: 'Men',
      cat_3: 'Tops',
      cat_4: 'Hoodies & Sweatshirts',
      collections: 'Eco Friendly',
      image_1: 'mh01-black_main.jpg',
      size: 'M',
      color: 'Black',
    },
    {
      id: '53',
      name: 'Frankie  Sweatshirt-S-Green',
      IsFeatured: '0',
      inStock: '0',
      stock: '0',
      price: '60',
      cat_1: 'Clothing',
      cat_2: 'Men',
      cat_3: 'Tops',
      cat_4: 'Hoodies & Sweatshirts',
      collections: 'Eco Friendly',
      image_1: 'mh04-green_main.jpg',
      image_2: 'mh04-green_alt1.jpg',
      size: 'M',
      color: 'Green',
    },
    {
      id: '21',
      name: 'Teton Pullover Hoodie-S-Black',
      IsFeatured: '0',
      inStock: '1',
      stock: '30',
      price: '70',
      cat_1: 'Clothing',
      cat_2: 'Men',
      cat_3: 'Tops',
      cat_4: 'Hoodies & Sweatshirts',
      image_1: 'mh02-black_main.jpg',
      image_2: 'mh02-black_alt1.jpg',
      size: 'L',
      color: 'Black',
    },
  ],

  item: [
    {
      id: '5',
      name: 'Chaz Kangeroo Hoodie-S-Black',
      IsFeatured: '0',
      inStock: '0',
      stock: '0',
      price: '52',
      cat_1: 'Clothing',
      cat_2: 'Men',
      cat_3: 'Tops',
      cat_4: 'Hoodies & Sweatshirts',
      collections: 'Eco Friendly',
      image_1: 'mh01-black_main.jpg',
      size: 'M',
      color: 'Black',
    },
    {
      id: '37',
      name: 'Bruno Compete Hoodie-S-Black',
      IsFeatured: '0',
      inStock: '1',
      stock: '60',
      price: '63',
      cat_1: 'Clothing',
      cat_2: 'Men',
      cat_3: 'Tops',
      cat_4: 'Hoodies & Sweatshirts',
      collections: 'Eco Friendly',
      image_1: 'mh03-black_main.jpg',
      image_2: 'mh03-black_alt1.jpg',
      size: 'M',
      color: 'Black',
    },
    {
      id: '53',
      name: 'Frankie  Sweatshirt-S-Green',
      IsFeatured: '0',
      inStock: '0',
      stock: '0',
      price: '60',
      cat_1: 'Clothing',
      cat_2: 'Men',
      cat_3: 'Tops',
      cat_4: 'Hoodies & Sweatshirts',
      collections: 'Eco Friendly',
      image_1: 'mh04-green_main.jpg',
      image_2: 'mh04-green_alt1.jpg',
      size: 'M',
      color: 'Green',
    },
    {
      id: '21',
      name: 'Teton Pullover Hoodie-S-Black',
      IsFeatured: '0',
      inStock: '1',
      stock: '30',
      price: '70',
      cat_1: 'Clothing',
      cat_2: 'Men',
      cat_3: 'Tops',
      cat_4: 'Hoodies & Sweatshirts',
      image_1: 'mh02-black_main.jpg',
      image_2: 'mh02-black_alt1.jpg',
      size: 'L',
      color: 'Black',
    },
  ],

  filter: {
    price: {
      min: 18,
      max: 99,
    },
    stock: {
      min: 0,
      max: 110,
    },
    cat_4: [
      'Hoodies & Sweatshirts',
      'Jackets',
      'Tees',
      'Tanks',
      'Bras & Tanks',
    ],
    color: [
      'White',
      'Gray',
      'Black',
      'Blue',
      'Brown',
      'Green',
      'Lavender',
      'Orange',
      'Purple',
      'Red',
      'Yellow',
    ],
    size: ['L', 'M', 'S'],
    featured: false,
    in_stock: true,
  },

  filterSize: {
    price: {
      min: 18,
      max: 99,
    },
    stock: {
      min: 0,
      max: 110,
    },
    cat_4: [
      'Hoodies & Sweatshirts',
      'Jackets',
      'Tees',
      'Tanks',
      'Bras & Tanks',
    ],
    color: [
      'White',
      'Gray',
      'Black',
      'Blue',
      'Brown',
      'Green',
      'Lavender',
      'Orange',
      'Purple',
      'Red',
      'Yellow',
    ],
    size: ['L'],
    featured: false,
    in_stock: false,
  },

  filterColor: {
    price: {
      min: 18,
      max: 99,
    },
    stock: {
      min: 0,
      max: 110,
    },
    cat_4: [
      'Hoodies & Sweatshirts',
      'Jackets',
      'Tees',
      'Tanks',
      'Bras & Tanks',
    ],
    color: ['White'],
    size: ['L', 'M', 'S'],
    featured: false,
    in_stock: false,
  },
};

export default testObjBase;
